apiVersion: v1
kind: Service
metadata:
  name: example-centos7-svc
spec:
  type: NodePort
  selector:
    kubevirt.io/domain: myvmi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30200
    
