apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-centos7
  labels:
    app: containerized-data-importer 
spec:
  storageClassName: hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data2"
